FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
COPY src/services/swagger/swagger-docs.yaml ./src/services/swagger/swagger-docs.yaml
RUN npm ci
COPY . .
RUN npm run build
FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/src/services/swagger/swagger-docs.yaml ./src/services/swagger/swagger-docs.yaml
ENV NODE_ENV=production
ENV PORT=3001
ENV JWT_SEC=eh21ry32rfqwdmfewuify34789wwqihddqwjbkjbc2ih32iufbqwidnqwk
ENV MONGO_PUBLIC_URL=mongodb+srv://ninjascodeuser:m9VGKjS68pAuJOeB@cluster0.rwmmtk6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
EXPOSE 3001
CMD ["node", "dist/server.js"]